.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "IND" "1" "April 2023" "" ""
.
.SH "NAME"
\fBind\fR \- calculates dates for uncommon dating systems/calendars
.
.SH "SYNOPSIS"
\fBind\fR [\-anfcpekjrzuxiqb] [\-y year] [\-m month] [\-d day|fuzzy date|y\-m\-d] [\-hHvlBCDU?]
.
.SH "DESCRIPTION"
\fBind\fR is a bash script which calculates the Byzantine year, indiction for current and Byzantine year, the Buddhist year, the year from the founding of the City of Rome, the Masoretic year, and the Japanese Imperial year\.
.
.P
Lunar\-solar calculations include: metonic cycle, epact, dominical year, Chinese year and New Year, and Buddhist observances in the Theravadan tradition\. Astronomical dating includes current Julian Period and Truncated Julian Date\.
.
.P
Other obscure and idiosyncratic dating systems and calendar support has also been added\.
.
.SH "OPTIONS"
.
.TP
\fB\-a\fR
Display all\.
.
.TP
\fB\-n\fR
Display none\.
.
.TP
\fB\-f\fR
Toggle Full common date\.
.
.TP
\fB\-c\fR
Toggle Common year\.
.
.TP
\fB\-p\fR
Toggle Hanke\-Henry date\.
.
.TP
\fB\-e\fR
Toggle Discordian year\.
.
.TP
\fB\-k\fR
Toggle Klock\.
.
.TP
\fB\-j\fR
Toggle Hebrew year\.
.
.TP
\fB\-r\fR
Toggle year of Rome\.
.
.TP
\fB\-z\fR
Toggle Byzantine year\.
.
.TP
\fB\-u\fR
Toggle Julian Period\.
.
.TP
\fB\-x\fR
Toggle Masoretic year(s)\.
.
.TP
\fB\-i\fR
Toggle Japanese Imperial year\.
.
.TP
\fB\-q\fR
Toggle Chinese Lunar year\.
.
.TP
\fB\-b\fR
Toggle Buddhist year\.
.
.TP
\fB\-y\fR
Set year in format \'yyyy\'\.
.
.TP
\fB\-m\fR
Set month in format \'m\'\.
.
.TP
\fB\-d\fR
Set day in format \'d\'\. Also accepts fuzzy dates, e\.g\. \'yesterday\', \'today\', \'tomorrow\', and y\-m\-d specifications\.
.
.TP
\fB\-h\fR
Toggle display of holidays\.
.
.TP
\fB\-H\fR
Enable highlighting\.
.
.TP
\fB\-v\fR
Verbose mode / diagnostics\.
.
.TP
\fB\-l\fR
Lunar diagnostic data\.
.
.TP
\fB\-B\fR
Buddhist observances\.
.
.TP
\fB\-C\fR
Chinese NY diagnostics\.
.
.TP
\fB\-D\fR
Check dependencies\.
.
.TP
\fB\-?\fR
Usage summary\.
.
.SH "NOTES"
.
.SS "A brief history of dating systems (source: Wikipedia)"
The Hebrew or Jewish calendar is a lunisolar calendar used today predominantly for Jewish religious observances\. The principles and rules were fully codified by Maimonides whose work also replaced counting "years since the destruction of the Temple" with the modern creation\-era Anno Mundi\. The Hebrew lunar year is about eleven days shorter than the solar cycle and uses the 19\-year Metonic cycle to bring it into line, with the addition of an intercalary month every two or three years\. It dates to 3760 BCE\.
.
.P
"Ab urbe condita" (also "anno urbis", a\.u\.) or "from the founding of the City (Rome)", is traditionally dated to 753 BCE\. AUC is a year\-numbering system used by historians of ancient Rome to identify particular years\. The dominant method of identifying years in Roman times was to name the two consuls who held office that year\. The regnal year of the emperor was also used to identify years, especially in the Byzantine Empire after 537\.
.
.P
The Byzantine calendar also "Creation Era of Constantinople," or "Era of the World" (Anno Mundi) was the calendar used by the Eastern Orthodox Church from c\. 691 to 1728 in the Ecumenical Patriarchate\. It was also the official calendar of the Byzantine Empire from 988 to 1453, and in Russia from c\. 988 to 1700\. The calendar is based on the Julian calendar except that the year started on 1 September and the year number used an Anno Mundi epoch\. Its year one, from creation, was September 1 5509 BCE to August 31 5508 BCE\.
.
.P
An indiction is any of the years in a 15\-year cycle used to date medieval documents throughout Europe, both East and West\. Each year of a cycle was numbered: first indiction, second indiction, etc\. However, the cycles were not numbered, thus other information is needed to identify specific years\.
.
.P
The Julian period or the Julian Day system provides astronomers with a single system of dates that could be used when working with different calendars to align different historical chronologies\. It assigns a Julian Day (JD) to every year without having to worry about BCE or CE\. It was invented by French Scholar Joseph Justus Scaliger in 1583, who proposed that the Julian Period starts at noon on January 1, 4713 BCE\. (Julian calendar) and lasts for 7980 years\.
.
.P
The Japanese imperial year or "national calendar year" is a unique calendar system in Japan\. It is based on the legendary foundation of Japan by Emperor Jimmu in 660 BCE, and emphasizes the long history of Japan and the Imperial dynasty\.
.
.P
The traditional Chinese calendar (officially known as the Agricultural Calendar, Former Calendar, Traditional Calendar, or Lunar Calendar), is a lunisolar calendar which reckons years, months, and days according to astronomical phenomena\. Although modern\-day China uses the Gregorian calendar, the traditional Chinese calendar governs holidays (such as the Chinese New Year and Lantern Festival) in both China and in overseas Chinese communities\.
.
.P
The Buddhist calendar is a set of lunisolar calendars primarily used in mainland Southeast Asian countries of Cambodia, Laos, Myanmar and Thailand as well as in Sri Lanka for religious and/or official occasions\. In Thailand, the name Buddhist Era is a year numbering system shared by the traditional Thai lunisolar calendar and by the Thai solar calendar\.
.
.P
Dominical letters or Sunday letters are a method used to determine the day of the week for particular dates\. When using this method, each year is assigned a letter (or pair of letters for leap years) depending on which day of the week the year starts on\.
.
.P
A golden number is a number assigned to each year in sequence which is used to indicate the dates of all the calendric new moons for each year in a 19\-year Metonic cycle\. They are used in computus (the calculation of the date of Easter) and also in Runic calendars\.
.
.P
Epact: If a solar and lunar year start on the same day, then after one year, the start of the solar year is 11 days after the start of the lunar year\. These excess days are epacts, and are added to the day of the solar year to determine the day of the lunar year\.
.
.P
Ides: a day in the Roman calendar that marked the approximate middle of the month\.
.
.SS "Julian Dates"
The Modified Julian Date (MJD) is an abbreviated version of the old Julian Day (JD) dating method which has been in use for centuries by astronomers, geophysicists, chronologers, and others who needed to have an unambiguous dating system based on continuing day counts\. It is counted from November 17, 1858\.
.
.P
The Truncated Julian Date (TJD) was introduced by NASA in 1979 as part of a parallel grouped binary time code (PB\-5) "designed specifically, although not exclusively, for spacecraft applications"\. TJD was a 4\-digit day count from MJD 44000, which was May 24, 1968, represented as a 14\-bit binary number\. Later PB\-5J was introduced which increased the TJD field to 16 bits, allowing values up to 65535, which occurs in the year 2147\.
.
.P
Rata Die (RD) is a system for assigning numbers to calendar days (optionally with time of day), independent of any calendar, for the purposes of calendrical calculations\. Rata Die, from the Latin "day of calculation", is counted from the first day of the Common Era (0001\-01\-01) in the proleptic Gregorian calendar\.
.
.SS "Masoretic Dates"
The Masoretic calendar (Anno Lucis) is a dating system used in ceremonial or commemorative proceedings, which is equivalent to the Gregorian year plus 4000\. It is similar to Anno Mundi\.
.
.SS "Quarter and Cross Quarter Days"
In British and Irish tradition, the quarter days were the four dates in each year on which servants were hired, school terms started, and rents were due\.
.
.P
The quarter days are: Lady Day (25 March), Midsummer Day (24 June), Michaelmas (29 September), Christmas (25 December)\.
.
.P
Lady Day is also referred to as the Feast of the Annunciation\.
.
.P
Michaelmas is also known as the Feast of Saints Michael, Gabriel, and Raphael, the Feast of the Archangels, or the Feast of Saint Michael and All Angels\.
.
.P
The cross\-quarter days are four holidays falling in between the quarter days: Candlemas (2 February), May Day (1 May), Lammas (1 August), and All Hallows (1 November)\.
.
.SS "Scottish Term and Quarter Days"
The Old Scottish Term and Quarter Days are: Candlemas (2 February), Whitsun (15 May), Lammas (1 August), and Martinmas (11 November)\.
.
.P
Candlemas originally fell on 2 February, the day of the Feast of the Purification, or the Presentation of Christ\. This was celebrated in pre\-Reformation times by candlelit processions\. The tradition was started in the 5th century during the Roman celebration of Februa, and carried over into Scotland, where mothers of children born the previous year would march with candles, hoping to be purified by the Virgin Mary\.
.
.P
Whitsun was originally the Feast of Pentecost, around which a great many christenings would occur, so it became associated with the colour white\. Because the date of Pentecost moves each year, the legal Term Day of Whitsun was fixed in Scotland as 26 May in the Julian Calendar, which became 15 May under the Gregorian Calendar, adopted in Scotland in 1599\.
.
.P
Lammas was celebrated on 1 August, the day the first fruits of the harvest were offered, the name coming from the Anglo\-Saxon for \'loaf\-mass\' or \'bread\-feast\'\.
.
.P
Martinmas, on 11 November, was originally the Feast of Saint Martin of Tours, a 4th\-century bishop and hermit\.
.
.P
In Scotland, 1886 saw the term dates for removals and the hiring of servants in towns changed to 28 February, 28 May, 28 August and 28 November\. The original dates are now referred to as Old Scottish Term Days\. The dates were regularised by the Term and Quarter Days (Scotland) Act 1990\.
.
.SS "Uposatha"
The Uposatha (Sanskrit: Upavasatha) is a Buddhist day of observance, in existence from the Buddha\'s time (500 BCE), and still being kept today in Buddhist countries\. The Buddha taught that the Uposatha day is for "the cleansing of the defiled mind", resulting in inner calm and joy\. On this day, lay disciples and monks intensify their practice, deepen their knowledge and express communal commitment through millennia\-old acts of lay\-monastic reciprocity\. On these days, the lay followers make a conscious effort to keep the Five Precepts or (as the tradition suggests) the Eight Precepts\. It is a day for practicing the Buddha\'s teachings and meditation\.
.
.P
There are four \'special\' full moon Uposatha: Magha Puja or Sangha day (February), Vesak or Buddha day (May), Asalha Puja or Dhamma day (July), and Pavarana (October)\.
.
.SS "Hanke\-Henry Permanent Calendar"
One of many examples of leap week calendars, calendars which maintain synchronization with the solar year by intercalating entire weeks rather than single days\. By reducing common years to 364 days (52 weeks), and adding an extra week every five or six years, the Hanke\-Henry Permanent Calendar eliminates weekday drift and synchronizes the calendar year with the seasonal change as the Earth circles the Sun\. As part of the calendar proposal, time zones would be eliminated and replaced with UTC\.
.
.SS "Discordian Calendar"
The Discordian or Erisian calendar is an alternative calendar used by some adherents of Discordianism\. The Discordian year 1 YOLD is 1166 BCE\. As described in the \fIPrincipia Discordia\fR, the Discordian calendar has five 73\-day seasons: Chaos, Discord, Confusion, Bureaucracy, and The Aftermath\. The Discordian year is aligned with the Gregorian calendar and begins on January 1\.
.
.P
The Discordian clock is an alternative time system derived from the Erisian Klock specification\.
.
.SH "AUTHOR"
Paul J Henry \fIcpjhenry@gmail\.com\fR
.
.SH "SEE ALSO"
ddate(1), hebcal(1), hh(1), jday(1), uposatha(7)
