#!/usr/bin/env bash
# Convert to/from Roman numerals
# Dennis Williamson / https://www.linuxjournal.com/content/converting-decimals-roman-numerals-bash
# retrieved 2019-05-14 / modified 2019-05-19/pjh

input=$(echo $1 | sed 's/.*/\U&/' | sed '/^$/d')
[[ ! $input ]] && exit

declare -A r2d=(
	[I]=1
	[IV]=4
	[V]=5
	[IX]=9
	[X]=10
	[XL]=40
	[L]=50
	[XC]=90
	[C]=100
	[CD]=400
	[D]=500
	[CM]=900
	[M]=1000
)

# build decimal to roman array from roman to decimal array
for element in "${!r2d[@]}"
do
	d2r[r2d[$element]]=$element
done

decimal2roman () {
	local decimal=$1 save=$1 indices=("${!d2r[@]}") n=${#indices[@]} roman
	for (( i = n - 1; i >= 0; i-- ))
	do
		while (( decimal >= indices[i] ))
		do
			if (( ( temp = decimal - indices[i] ) >= 0 ))
			then
				decimal=$temp
				roman+=${d2r[indices[i]]}
			fi
		done
	done
	echo $roman
}

roman2decimal () {
	local roman=${1^^} decimal
	for (( i = 0; i < ${#roman}; i++ ))
	do
		if (( d = r2d[${roman:i:2}] ))
		then
			(( decimal += d, i++ ))
		else
			(( decimal += r2d[${roman:i:1}] ))
		fi
	done
	echo $decimal
}

# main()
if [ "$(echo $input | grep "[IVXLCDM]")" ]; then
	roman2decimal $input
else
	decimal2roman $input
fi
