.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "UPOSATHA" "7" "February 2021" "" ""
.
.SH "NAME"
\fBuposatha\fR \- (info) Uposatha Days
.
.SH "Day of observance"
The Uposatha (Sanskrit: Upavasatha) is a Buddhist day of observance, in existence from the Buddha\'s time\. The Buddha taught that the Uposatha day is for "the cleansing of the defiled mind," resulting in inner calm and joy\.
.
.P
On this day, both lay and ordained members of the sangha intensify their practice, deepen their knowledge and express communal commitment through millennia\-old acts of lay\-monastic reciprocity\. On these days, the lay followers make a conscious effort to keep the Five Precepts or (as the tradition suggests) the Eight Precepts\. It is a day for practicing the Buddha\'s teachings and meditation\.
.
.P
In general, Uposatha is observed about once a week in Theravadin countries in accordance with the four lunar phases: the new moon, the full moon, and the two quarter moons in between\. In some communities, such as in Sri Lanka, only the new moon and full moon are observed as uposatha days\.
.
.SH "Special Uposatha days"
There are four \'special\' full moon Uposatha:
.
.IP "" 4
.
.nf

\- Sangha day (February)
\- Buddha day (May)
\- Dhamma day (July)
\- Pavarana (October)
.
.fi
.
.IP "" 0
.
.TP
Magha Puja or Magha Uposatha ("Sangha Day")
Anniversary of the assembling of 1250 monks in the Buddha\'s presence during which time he delivered the "Ovada\-Patimokkha Gatha"\.
.
.TP
Visakha Puja or Visakha Uposatha or Vesak ("Buddha Day")
The most sacred Buddhist holiday\. It is the anniversary of the Buddha\'s birth, awakening and parinibbana\.
.
.TP
Asalha Puja or Asalha Uposatha ("Dhamma Day")
Anniversary of the Buddha\'s delivering his first discourse, which is collected as the Dhammacakkappavattana Sutta\. The three\-month\-long Vassa retreat starts the following day\.
.
.TP
Pavarana
End of the Rains Retreat residence during which time each monk atones before the Sangha for any offense they may have committed\.

