#!/bin/bash
# Commit using latest version as comment
# 2024-06-23

latestversion=$(head ChangeLog.org |grep -m1 '^\*' |cut -f2 -d" ")

echo -n "Synchronizing with github ... "
git status |sed "s/On branch/on branch/;/(use/d;/Your branch is up to date with/d;/^$/d"
if [ "$(git status |grep -i "untracked")" ]; then git add -A; fi
if [ "$(git status |grep -i "committed")" ]; then echo; git commit -am "$latestversion"; fi
if [ "$(git status |grep -i "is ahead")" ];  then echo; git push; fi

find . -type f -name '*.DS_Store' -ls -delete
